name = "openai-proxy"
compatibility_date = "2023-01-01"

kv_namespaces = [
    { binding = "OPENAI_CACHE", id = "3c3c09b085d5475d9da26a4af70d3b01", preview_id = "3c3c09b085d5475d9da26a4af70d3b01" }
]


